image: docker:20

stages:
    - format
    - lint
    - test
    - build
    - push

services:
    - docker:dind

before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

# Client jobs

lint-client:
    stage: lint
    script:
        - cd client
        - docker build --target lint -t hivexplore/client .

test-client:
    stage: test
    needs: [lint_client]
    script:
        - cd client
        - docker build --target test -t hivexplore/client .

build-client:
    stage: build
    needs: [test_client]
    script:
        - cd client
        # - docker build -t hivexplore/client .

push-client:
    stage: push
    needs: [build_client]
    script:
        - cd client
        - echo allo

# Server jobs

format-server:
    stage: format
    script:
        - cd server
        # - docker build --target format -t hivexplore/server .

lint-server:
    stage: lint
    needs: [format_server]
    script:
        - cd server
        # - docker build --target lint -t hivexplore/server .

test-server:
    stage: test
    needs: [lint_server]
    script:
        - cd server
        # - docker build --target test -t hivexplore/server .

push-server:
    stage: push
    needs: [test_server]
    script:
        - cd server
        - echo allo

# Drone jobs

format-drone:
    stage: format
    script:
        - cd drone
        # - docker build --target format -t hivexplore/drone .

build-drone:
    stage: build
    needs: [format_drone]
    script:
        - cd drone
        # - docker build -t hivexplore/drone .

push-drone:
    stage: push
    needs: [build_drone]
    script:
        - cd drone
        - echo allo

# ARGoS jobs

format-argos:
    stage: format
    script:
        - cd argos
        # - docker build --target format -t hivexplore/argos .

build-argos:
    stage: build
    needs: [format_argos]
    script:
        - cd argos
        # - docker build -t hivexplore/argos .

push-argos:
    stage: push
    needs: [build_argos]
    script:
        - cd argos
        - echo allo
