image: docker:20

stages:
    - format
    - lint
    - test
    - build

services:
    - docker:dind

variables:
    IMAGE_NAME: $CI_REGISTRY/polytechnique-montr-al/inf3995/20211/equipe-102/hivexplore

before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

# Client jobs

lint-client:
    stage: lint
    script:
        - docker pull $IMAGE_NAME/client:ci || true
        - cd client
        - docker build --cache-from $IMAGE_NAME/client:ci --target lint --tag $IMAGE_NAME/client:ci .
        - docker push $IMAGE_NAME/client:ci
    only:
        - gitlab-ci # TODO: remove me
        - master
        - merge_requests

test-client:
    stage: test
    needs: [lint_client]
    script:
        - docker pull $IMAGE_NAME/client:ci || true
        - cd client
        - docker build --cache-from $IMAGE_NAME/client:ci --target test --tag $IMAGE_NAME/client:ci .
        - docker push $IMAGE_NAME/client:ci

build-client:
    stage: build
    needs: [test_client]
    script:
        - docker pull $IMAGE_NAME/client:ci || true
        - cd client
        - docker build --cache-from $IMAGE_NAME/client:ci --tag $IMAGE_NAME/client:ci .
        - docker push $IMAGE_NAME/client:ci

# Server jobs

# format-server:
#     stage: format
#     script:
#         - cd server
#         - docker build --target format .
    # only:
    #     - gitlab-ci # TODO: remove me
    #     - master
    #     - merge_requests

# lint-server:
#     stage: lint
#     needs: [format_server]
#     script:
#         - cd server
#         - docker build --target lint .

# test-server:
#     stage: test
#     needs: [lint_server]
#     script:
#         - cd server
#         - docker build --target test .

# # Drone jobs

# format-drone:
#     stage: format
#     script:
#         - cd drone
#         - docker build --target format .
    # only:
    #     - gitlab-ci # TODO: remove me
    #     - master
    #     - merge_requests

# build-drone:
#     stage: build
#     needs: [format_drone]
#     script:
#         - cd drone
#         - docker build -t hivexplore/drone .

# # ARGoS jobs

# format-argos:
#     stage: format
#     script:
#         - cd argos
#         - docker build --target format .
    # only:
    #     - gitlab-ci # TODO: remove me
    #     - master
    #     - merge_requests

# build-argos:
#     stage: build
#     needs: [format_argos]
#     script:
#         - cd argos
#         - docker build .
