image: docker

stages:
    - format
    - lint
    - test
    - build

before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

# Server jobs

format_server:
    stage: format
    services:
        - docker:dind
    script:
        - cd server
        - docker build --target format -t hivexplore/server .

lint_server:
    stage: lint
    services:
        - docker:dind
    needs: [format_server]
    script:
        - echo allo

test_server:
    stage: test
    services:
        - docker:dind
    needs: [lint_server]
    script:
        - echo allo

# Client jobs

lint_client:
    stage: lint
    services:
        - docker:dind
    script:
        - cd client
        - docker build --target lint -t hivexplore/client .

test_client:
    stage: test
    services:
        - docker:dind
    needs: [lint_client]
    script:
        - echo allo

build_client:
    stage: build
    services:
        - docker:dind
    needs: [test_client]
    script:
        - echo allo

# Drone jobs

format_drone:
    stage: format
    services:
        - docker:dind
    script:
        - cd drone
        - docker build --target format -t hivexplore/drone .

build_drone:
    stage: build
    services:
        - docker:dind
    needs: [format_drone]
    script:
        - echo allo

# ARGoS jobs

format_argos:
    stage: format
    services:
        - docker:dind
    script:
        - cd argos
        - docker build --target format -t hivexplore/argos .

build_argos:
    stage: build
    services:
        - docker:dind
    needs: [format_argos]
    script:
        - echo allo
