version: "3.8"

services:
    server:
        command: argos
        volumes:
            - socket:/tmp/hivexplore # TODO: Document this directory

    argos:
        build: ./argos
        image: hivexplore/argos
        volumes:
            - $XSOCKET:$XSOCKET
            - $XAUTHORITY:$XAUTHORITY
            - socket:/tmp/hivexplore # TODO: Document this directory (in ARGoS README for make start commands)
        environment:
            DISPLAY: $DISPLAY
            XAUTHORITY: $XAUTHORITY

volumes:
    socket:
