version: "3.8"

services:
    client:
        build: ./client
        image: hivexplore/client
        ports:
            - 3995:80

    server:
        build: ./server
        image: hivexplore/server
        ports:
            - 5678:5678
        volumes:
            - logs:/hivexplore/logs # TODO: Change server code to use different directory (env variable maybe?)

volumes:
    logs:
    # TODO: Rename volumes?
    # TODO: Fix permission issue, maybe this link: https://stackoverflow.com/questions/24288616/permission-denied-on-accessing-host-directory-in-docker

