version: "3.8"

services:
    client:
        build: ./client
        image: hivexplore/client
        ports:
            - 3995:80

    server:
        build: ./server
        image: hivexplore/server
        command: argos # TODO: Crazyflie vs ARGoS args? How to pass args to Docker Compose?
        ports:
            - 5678:5678
        volumes:
            - /tmp/hivexplore:/tmp/hivexplore # TODO: Document this directory
            - /tmp/logs:/hivexplore/logs # TODO: Change server code to use different directory (env variable maybe?)

    argos:
        build: ./argos
        image: hivexplore/argos
        volumes:
            - $XSOCKET:$XSOCKET
            - $XAUTHORITY:$XAUTHORITY
            - /tmp/hivexplore:/tmp/hivexplore # TODO: Document this directory
        environment:
            DISPLAY: $DISPLAY
            XAUTHORITY: $XAUTHORITY
