version: "3.8"

services:
    client:
        build: ./client
        image: hivexplore/client
        ports:
            - 3995:80

    server:
        build: ./server
        image: hivexplore/server
        command: argos # TODO: Crazyflie vs ARGoS args? How to pass args to Docker Compose?
        ports:
            - 5678:5678
        volumes:
            - socket:/tmp/hivexplore # TODO: Document this directory # TODO: Check if /tmp/ is conventional for socket location inside container
            - logs:/hivexplore/logs # TODO: Change server code to use different directory (env variable maybe?)

    argos:
        build: ./argos
        image: hivexplore/argos
        volumes:
            - $XSOCKET:$XSOCKET
            - $XAUTHORITY:$XAUTHORITY
            - socket:/tmp/hivexplore # TODO: Document this directory
        environment:
            DISPLAY: $DISPLAY
            XAUTHORITY: $XAUTHORITY

volumes:
    socket:
    logs:
    # TODO: Rename volumes?
    # TODO: Multiple volumes or one volume?
    # TODO: Fix permission issue, maybe this link: https://stackoverflow.com/questions/24288616/permission-denied-on-accessing-host-directory-in-docker
