DRONE_NAMES = [
    'Nathanamiel',
    'Waspy Willy',
    'Pierre-Hive',
    'Isabeille',
    'Cardi Bee',
    'Beeyoncé',
    'Honey Hermione',
    'Beethoven',
    'Buzzy Barry',
    'Hive Harry',
    'Yellow Yone',
    'Stripped Sam',
    'Stingy Sarah',
    'Beelie Eilish',
    'Justin Beeber',
    'Nectar Nelson',
    'Bambee',
]
